apiVersion: charts.hub.docker.com/v1alpha1
kind: Arklb
metadata:
  name: arklb-sample
spec:
  # Default values copied from <project_dir>/helm-charts/arklb/values.yaml
  replicaCount: 2
  affinity: {}
  autoscaling:
    enabled: false
    maxReplicas: 10
    minReplicas: 1
  image:
    pullPolicy: IfNotPresent
    repository: aerox86/arklb
    tag: latest
    tty: true
  imagePullSecrets: []
  ingress:
    annotations: {}
    className: ""
    enabled: false
    hosts:
    - host: chart-example.local
      paths:
      - path: /
        pathType: ImplementationSpecific
    tls: []
  nodeSelector: {}
  podAnnotations: {}
  podSecurityContext: {}
  resources: {}
  restartPolicy: Always
  securityContext:
    privileged: true
  service:
    port: 8081
    type: NodePort
  serviceAccount:
    annotations: {}
    create: true
    name: arklb
  tolerations: []
