apiVersion: dev.ark7.github.io/v1alpha1
kind: Ark
metadata:
  name: ark-sample
  namespace: default
spec:
  # Default values copied from <project_dir>/helm-charts/arklb/values.yaml
  replicaCount: 1
  affinity: {}
  autoscaling:
    enabled: false
    maxReplicas: 10
    minReplicas: 1
  image:
    pullPolicy: IfNotPresent
    repository: aerox86/arklb
    tty: true
  imagePullSecrets: []
  ingress:
    annotations: {}
    className: ""
    enabled: false
    hosts:
    - host: chart-example.local
      paths:
      - path: /
        pathType: ImplementationSpecific
    tls: []
  nodeSelector: {}
  podAnnotations: {}
  podSecurityContext: {}
  resources: {}
  restartPolicy: Always
  securityContext:
    privileged: true
  service:
    port: 8080
    type: ClusterIP
  serviceAccount:
    annotations: {}
    create: false
    name: ark
  tolerations: []
  